.gitignore
api/app/routers/land_change/dist_alerts/dist_alerts.py
api/test/integration/test_dist_analytics.py
api/test/unit/test_dist_analytics.py

A small PR to get the tests and linting working. In order to run tests from root directory in app folder, using full path for imports instead of relative.

Get KBA integration test working, use full paths in module imports, fix linting issues

---

.github/workflows/build-test-deploy.yml

Fix TF deploy

---

.github/workflows/build-test-deploy.yml

Can't specify vars with saved plan

---

terraform/main.tf

Add locking to TF backend

---

.github/workflows/build-test-deploy.yml

Fix deploy: Must re-checkout code in later job

---

.github/workflows/test-on-push.yml

Fix branches exclude/ignore issue

---

api/test/integration/analysis/dist_alerts/test_analysis.py

Merging custom aois PR surfaced this issue where we are not passing correct arguments to zonal_statistics function

fix dist analytics test

---

.github/workflows/build-test-deploy.yml
api/app/routers/common_analytics.py
terraform/main.tf
terraform/variables.tf

This is temporary while we debug permissions
-
-
-

chore: verify duckdb access to s3 in zeno

---

api/app/domain/analyzers/tree_cover_analyzer.py
api/app/domain/compute_engines/handlers/precalc_implementations/precalc_handlers.py
api/app/models/land_change/tree_cover.py
api/app/routers/land_change/tree_cover/tree_cover.py
api/test/unit/models/land_change/test_tree_cover.py
api/test/unit/routers/land_change/tree_cover/test_tree_cover.py

… keep using Dummy for now
-
-
-

Add proper impl for Tree Cover analysis on top of Gary's changes, but keep using Dummy for the moment

---

api/app/infrastructure/persistence/aws_dynamodb_s3_analysis_repository.py
api/app/infrastructure/persistence/file_resource.py
api/app/models/common/analysis.py
api/app/routers/common_analytics.py
api/test/integration/analysis/tree_cover_gain/test_tree_cover_gain.py
api/test/integration/analysis/tree_cover_loss/test_tree_cover_loss.py
api/test/integration/infrastructure/persistence/test_aws_dynamo_db_analysis_repository.py
api/test/integration/test_carbon.py
api/test/integration/test_land_cover_change.py
api/test/integration/test_nl_analytics.py
api/test/unit/models/land_change/test_carbon_flux.py
api/test/unit/models/land_change/test_tree_cover.py
api/test/unit/models/land_change/test_tree_cover_gain.py
api/test/unit/models/land_change/test_tree_cover_loss.py
api/test/unit/use_cases/analysis/test_analysis_service.py
pyproject.toml
terraform/main.tf
uv.lock

pzb-398/aws-analysis-repo

---

.gitignore
api/app/models/land_change/tree_cover.py
api/app/routers/common_analytics.py
api/app/routers/land_change/tree_cover/tree_cover.py
api/test/integration/analysis/tree_cover/test_tree_cover.py

Feat(TreeCover): Enable AWS Implementation for Tree Cover Analytics Resources

---

api/app/routers/land_change/tree_cover/tree_cover.py
api/test/integration/analysis/tree_cover/test_tree_cover.py

:art: refactor(TreeCover): update integration tests to not use AWS analysis repo

---

api/test/integration/test_dist_analytics.py
api/test/integration/test_nl_analytics.py

:white_check_mark: test(integration): relax some assertions around dataframes

---

api/app/models/land_change/tree_cover_gain.py
api/app/routers/land_change/tree_cover_gain/tree_cover_gain.py
api/test/integration/analysis/tree_cover_gain/test_tree_cover_gain.py

PZB-398: Use AWS AnalysisRepository for TreeCoverGain

---

api/app/analysis/common/analysis.py
api/app/domain/repositories/data_api_aoi_geometry_repository.py
api/test/unit/test_dist_analytics.py

chore(WDPA): Use `wdpa_pid` for Protected Areas

---

api/app/infrastructure/persistence/aws_dynamodb_s3_analysis_repository.py

chore(AnalysisRepository): Log Status of Loaded Resources

---

api/app/domain/analyzers/tree_cover_gain_analyzer.py
api/app/domain/compute_engines/handlers/otf_implementations/flox_otf_handler.py
api/app/domain/compute_engines/handlers/precalc_implementations/precalc_sql_query_builder.py
api/app/domain/models/dataset.py
api/app/domain/repositories/zarr_dataset_repository.py
api/test/integration/analysis/tree_cover_gain/test_tree_cover_gain.py
api/test/integration/domain/compute_engines/test_precalc_handler.py
api/test/unit/domain/analyzers/test_tree_cover_gain_analyzer.py
api/test/unit/models/test_dataset.py

I fixed the key error with TreeCoverGain, with minimal other changes (additional tests, and pre-commit reformatted a few lines).
Attempts to query tree cover gain over more than one five-year period fail
- One can query tree cover gain for any (single or multiple) five year period(s).

Fix key error for some params in tree cover gain

---

terraform/main.tf

Try specifying to create API logs

---

terraform/main.tf

Reverts wri/project-zeno-data-infra#150

Revert "Try specifying to create API logs"

---

api/app/domain/analyzers/carbon_flux_analyzer.py
api/app/routers/land_change/carbon_flux/carbon_flux.py
api/test/integration/test_carbon.py

Fix for https://gfw.atlassian.net/browse/PZB-486

move carbon flux parquet to aoi_id based pre-aggregated results

---

api/app/infrastructure/persistence/aws_dynamodb_s3_analysis_repository.py
api/app/models/land_change/tree_cover.py
api/app/models/land_change/tree_cover_gain.py
api/app/models/land_change/tree_cover_loss.py
api/test/integration/infrastructure/persistence/test_aws_dynamo_db_analysis_repository.py

PZB-512: Custom Areas Land Cover Change and Composition Analysis Failing

---

api/docker-compose-api.yml
terraform/main.tf

Remove api prefix from TF, docker compose
